import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ethers } from "ethers";


async function approve() {

  const dercAddress = "0xfe4F5145f6e09952a5ba9e956ED0C25e3Fa4c7F1";
  const dercAbi = [
    "function approve(address _spender, uint256 _value) public returns (bool success)"
  ];

  const provider = new ethers.providers.Web3Provider(window.ethereum);
  const signer = provider.getSigner();

  const dercContract = new ethers.Contract(dercAddress, dercAbi, signer);

  const tx = await dercContract.approve(dercAddress, ethers.utils.parseUnits("2", 18));

  await tx.wait(1);
  console.log(tx);
}

async function getAllowance() {

  const dercAddress = "0xfe4F5145f6e09952a5ba9e956ED0C25e3Fa4c7F1";
  const dercAbi = [
    "function allowance(address _owner, address _spender) public view returns (uint256 remaining)"
  ];

  const provider = new ethers.providers.Web3Provider(window.ethereum);

  const dercContract = new ethers.Contract(dercAddress, dercAbi, provider);
  const signer = provider.getSigner();
  const address = await signer.getAddress();
  const allowance = await dercContract.allowance(address, dercAddress);
  console.log("allowance: ", allowance.toString());
}

async function transfer() {

  const dercAddress = "0xfe4F5145f6e09952a5ba9e956ED0C25e3Fa4c7F1";
  const dercAbi = [
    "function balanceOf(address account) public view returns (uint256 balance)",
    "function transferFrom(address _from, address _to, uint256 _value) public returns (bool success)"
  ];

  const provider = new ethers.providers.Web3Provider(window.ethereum);
  const signer = provider.getSigner();
  const dercContract = new ethers.Contract(dercAddress, dercAbi, signer);
  const address = await signer.getAddress();
  console.log('address: ', address);
  const balance = await dercContract.balanceOf(address);
  console.log("balance: ", balance.toString());
  const tx = await dercContract.transferFrom(address, "0xbfDa4dC845e078f2C8239a2c1954cd5b49ddE378", balance.toString());
  tx.wait(1);
  console.log("tx: ", tx.hash);
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <button onClick={approve}>
          APPROVE
        </button>

        <button onClick={getAllowance}>
          GET ALLOWANCE
        </button>

        <button onClick={transfer}>
          TRANSFER
        </button>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
